### PR TITLE
separate build instructions

### PR DESCRIPTION
**Pull request by crumpetalpaca**
made build instructions separate file

### CODE REVIEW

**Comment by crumpetalpaca** [comment]
also set my git with the right account

**Comment by Tarkan-Zarrouk** [comment]
Garbage pull request, users can use the jar that is posted in the release or build by source which includes a step by step way to build it lmao

**Comment by Tarkan-Zarrouk** [comment]
Better if u close it

**Comment by Pr3roxDLC** [comment]
yeah no not really all that usefull

**Pull request closed without merging**
